import Head from 'next/head'
import useInView from 'react-cool-inview'
import dynamic from 'next/dynamic'

const Comments = dynamic(() => import('../Components/Comments'))

import styles from '../styles/Home.module.css'

export default function Home() {
  const { observe, inView } = useInView({
    onEnter: ({ unobserve }) => unobserve(),
  })

  console.log(inView)
  return (
    <>
      <Head>
        <title>NextLazyScrolling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>Scroll Down</div>

      <div className={styles.comments} ref={observe}>
        <h2>Comments</h2>
        {inView && <Comments />}
      </div>
    </>
  )
}
